eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
  instance:
    instance-id: springcloud63-product-8003
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
    
info:
  appName: this is my product module
  developName: DeYong
  data: 2020/4/6
  language: java
  ip: 192.168.224.224
  port: 8003    

spring:
  profiles: dev
  application:
    name: springcloud63-product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java63
    username: root
    password: 123456
server:
  port: 8003

mybatis:
  config-location: classpath:mybatis-config.xml